/*
 * File: app/view/MyWindow.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MiComidita.view.MyWindow', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.grid.View',
        'Ext.form.field.Text',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio'
    ],

    height: 579,
    hidden: false,
    width: 878,
    title: 'Mi comidita',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            height: 502,
                            layout: 'absolute',
                            title: 'CRUDS',
                            items: [
                                {
                                    xtype: 'tabpanel',
                                    x: 0,
                                    y: 0,
                                    height: 500,
                                    activeTab: 0,
                                    items: [
                                        {
                                            xtype: 'panel',
                                            height: 174,
                                            layout: 'absolute',
                                            title: 'Materias Primas',
                                            items: [
                                                {
                                                    xtype: 'tabpanel',
                                                    x: 0,
                                                    y: 0,
                                                    height: 470,
                                                    id: 'panelMaterias',
                                                    activeTab: 0,
                                                    items: [
                                                        {
                                                            xtype: 'panel',
                                                            layout: 'absolute',
                                                            title: 'Consulta',
                                                            items: [
                                                                {
                                                                    xtype: 'gridpanel',
                                                                    x: -1,
                                                                    y: 40,
                                                                    height: 390,
                                                                    title: 'Materias Primas',
                                                                    store: 'MyJsonStore',
                                                                    columns: [
                                                                        {
                                                                            xtype: 'gridcolumn',
                                                                            width: 258,
                                                                            dataIndex: 'Nombre',
                                                                            text: 'Nombre'
                                                                        },
                                                                        {
                                                                            xtype: 'gridcolumn',
                                                                            width: 261,
                                                                            dataIndex: 'Unidad',
                                                                            text: 'Unidad'
                                                                        },
                                                                        {
                                                                            xtype: 'gridcolumn',
                                                                            width: 224,
                                                                            dataIndex: 'Categoria',
                                                                            text: 'Categoria'
                                                                        },
                                                                        {
                                                                            xtype: 'gridcolumn',
                                                                            width: 126,
                                                                            dataIndex: 'precioUnidad',
                                                                            text: 'Precio Unidad'
                                                                        }
                                                                    ]
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    x: 10,
                                                                    y: 10,
                                                                    text: 'Agregar',
                                                                    listeners: {
                                                                        click: {
                                                                            fn: me.onButtonClick,
                                                                            scope: me
                                                                        }
                                                                    }
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    x: 90,
                                                                    y: 10,
                                                                    text: 'Modificar'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    x: 180,
                                                                    y: 10,
                                                                    text: 'Eliminar'
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'panel',
                                                            layout: 'absolute',
                                                            title: 'Datos',
                                                            items: [
                                                                {
                                                                    xtype: 'textfield',
                                                                    x: 20,
                                                                    y: 30,
                                                                    width: 820,
                                                                    fieldLabel: 'Nombre'
                                                                },
                                                                {
                                                                    xtype: 'radiogroup',
                                                                    x: 20,
                                                                    y: 80,
                                                                    width: 400,
                                                                    fieldLabel: 'Unidad',
                                                                    items: [
                                                                        {
                                                                            xtype: 'radiofield',
                                                                            boxLabel: 'Kg'
                                                                        },
                                                                        {
                                                                            xtype: 'radiofield',
                                                                            boxLabel: 'Litros'
                                                                        },
                                                                        {
                                                                            xtype: 'radiofield',
                                                                            boxLabel: 'Piezas'
                                                                        }
                                                                    ]
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            title: 'Recetas'
                                        },
                                        {
                                            xtype: 'panel',
                                            title: 'Productos elaborados'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            height: 513,
                            layout: 'absolute',
                            title: 'Consultas',
                            items: [
                                {
                                    xtype: 'tabpanel',
                                    x: 0,
                                    y: 0,
                                    activeTab: 0,
                                    items: [
                                        {
                                            xtype: 'panel',
                                            title: 'Tab 1'
                                        },
                                        {
                                            xtype: 'panel',
                                            title: 'Tab 2'
                                        },
                                        {
                                            xtype: 'panel',
                                            title: 'Tab 3'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        Ext.getCmp("panelMaterias").setActiveTab(1);
    }

});